/* Codexin Order Flow: market-data-first browser terminal.
 * Scope is intentionally one instrument and one venue: BTCUSDT USD-M Futures.
 * There is no Spot fallback and no execution path. Missing or invalid feeds
 * suppress authorization instead of manufacturing a signal.
 */
const CONFIG={symbol:"BTCUSDT",lower:"btcusdt",venue:"BINANCE",market:"USD-M FUTURES",rest:"https://fapi.binance.com/fapi/v1",ws:"wss://fstream.binance.com/stream?streams=",maxTrades:600,maxTape:28,bookLevels:18};
const state={interval:"1m",price:null,mark:null,index:null,prevClose:null,change24h:null,oi:null,funding:null,ratios:null,lastTradeAt:0,lastBookAt:0,lastTickerAt:0,lastKlineAt:0,lastOiAt:0,lastFundingAt:0,lastRatioAt:0,tradeCount:0,errors:0,events:[],trades:[],buckets:new Map(),klines:[],book:{bids:new Map(),asks:new Map(),lastUpdateId:null,lastEventId:null,valid:false,resyncs:0,queue:[],syncing:false},ws:null,chart:null,candleSeries:null,volumeSeries:null};
const $=id=>document.getElementById(id); const fmt=(n,d=2)=>Number.isFinite(Number(n))?Number(n).toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d}):"—"; const usd=n=>Number.isFinite(Number(n))?`$${fmt(n,0)}`:"—"; const pct=n=>Number.isFinite(Number(n))?`${Number(n).toFixed(2)}%`:"—"; const ago=t=>t?((Date.now()-t)/1000<10?`${Math.max(0,((Date.now()-t)/1000)).toFixed(1)}s`:`${Math.round((Date.now()-t)/1000)}s`):"—"; const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function log(message,kind="info"){state.events.unshift({time:new Date(),message,kind});state.events=state.events.slice(0,80);renderHealthLog();}
function setText(id,value){const el=$(id);if(el)el.textContent=value;}
function setClass(id,cls){const el=$(id);if(el)el.className=cls;}
async function json(url,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),options.timeout||8000);try{const r=await fetch(url,{signal:controller.signal,cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
function streamUrl(){return CONFIG.ws+[
  `${CONFIG.lower}@aggTrade`,`${CONFIG.lower}@depth@100ms`,`${CONFIG.lower}@kline_1m`,`${CONFIG.lower}@bookTicker`
].join("/")}
function openStream(){if(state.ws)try{state.ws.close()}catch{};state.ws=new WebSocket(streamUrl());setFeed("trades","CONNECTING");setFeed("orderbook","CONNECTING");state.ws.onopen=()=>{log("USD-M Futures WebSocket connected","good");setFeed("trades","LIVE");setFeed("orderbook",state.book.valid?"LIVE":"SYNCING");syncBook()};state.ws.onmessage=e=>{try{const m=JSON.parse(e.data),d=m.data||m,s=m.stream||"";if(s.includes("aggTrade"))onTrade(d);else if(s.includes("depth"))onDepth(d);else if(s.includes("kline"))onKline(d);else if(s.includes("bookTicker"))onBookTicker(d)}catch(err){state.errors++;log(`Stream parse error: ${err.message}`,"warn")}};state.ws.onerror=()=>{state.errors++;log("WebSocket error; reconnecting", "warn");setFeed("trades","ERROR");setFeed("orderbook","ERROR")};state.ws.onclose=()=>{setFeed("trades","RECONNECT");setFeed("orderbook","RECONNECT");setTimeout(openStream,1500)}}
async function syncBook(){if(state.book.syncing)return;state.book.syncing=true;setFeed("orderbook","SYNCING");try{const snap=await json(`${CONFIG.rest}/depth?symbol=${CONFIG.symbol}&limit=1000`,{timeout:8000});const b=state.book;b.bids=new Map(snap.bids.map(x=>[String(x[0]),Number(x[1])]).filter(x=>x[1]>0));b.asks=new Map(snap.asks.map(x=>[String(x[0]),Number(x[1])]).filter(x=>x[1]>0));b.lastUpdateId=Number(snap.lastUpdateId);b.lastEventId=null;b.valid=false;const q=b.queue.splice(0);for(const ev of q){if(Number(ev.u)<=b.lastUpdateId)continue;if(Number(ev.U)<=b.lastUpdateId+1&&Number(ev.u)>=b.lastUpdateId){if(!applyDepth(ev)){b.syncing=false;return syncBook()}b.valid=true;break}}if(!b.valid){b.queue=[];setFeed("orderbook","RESYNC");return setTimeout(()=>{b.syncing=false;syncBook()},350)}for(const ev of q){if(Number(ev.u)<=b.lastUpdateId)continue;if(!applyDepth(ev)){b.syncing=false;return syncBook()}}b.syncing=false;setFeed("orderbook","LIVE");state.lastBookAt=Date.now();log(`Order book synced at sequence ${b.lastUpdateId}`,"good");renderAll()}catch(err){bumpFeed("orderbook",`Order book sync failed: ${err.message}`);state.book.syncing=false;setTimeout(syncBook,2500)}}
function applyDepth(ev){const b=state.book;if(b.lastEventId!==null){if(ev.pu!==undefined&&Number(ev.pu)!==b.lastEventId){b.valid=false;b.resyncs++;log(`Order book sequence gap: pu=${ev.pu}, expected=${b.lastEventId}`,"warn");setTimeout(syncBook,50);return false}}else if(b.lastUpdateId!==null&&Number(ev.U)>b.lastUpdateId+1){b.valid=false;b.resyncs++;log("Order book gap detected; interval invalidated","warn");setTimeout(syncBook,50);return false}for(const [p,q] of ev.b||[]){const key=String(p),v=Number(q);if(v===0)b.bids.delete(key);else b.bids.set(key,v)}for(const [p,q] of ev.a||[]){const key=String(p),v=Number(q);if(v===0)b.asks.delete(key);else b.asks.set(key,v)}b.lastUpdateId=Number(ev.u);b.lastEventId=Number(ev.u);b.valid=true;state.lastBookAt=Date.now();return true}
function onDepth(d){const b=state.book;if(!b.valid){b.queue.push(d);if(b.queue.length>1200)b.queue.shift();return}if(!applyDepth(d)){b.valid=false;b.queue=[d];setFeed("orderbook","GAP");log("Order-book sequence gap; local book invalidated","warn");syncBook();return}renderBook();}
function onTrade(d){const price=Number(d.p),qty=Number(d.q),notional=price*qty,buy=!d.m,ts=Number(d.T)||Date.now();state.price=price;state.lastTradeAt=Date.now();state.tradeCount++;state.trades.unshift({price,qty,notional,buy,ts});state.trades=state.trades.slice(0,CONFIG.maxTrades);const bucket=Math.floor(ts/60000)*60000;let x=state.buckets.get(bucket);if(!x)x={time:bucket,buy:0,sell:0,price,high:price,low:price,count:0};x.price=price;x.high=Math.max(x.high,price);x.low=Math.min(x.low,price);x.count++;buy?x.buy+=notional:x.sell+=notional;state.buckets.set(bucket,x);if(state.buckets.size>90)state.buckets.delete([...state.buckets.keys()].sort((a,b)=>a-b)[0]);renderTape();renderFlow();renderHeader();renderDecision();}
function onKline(d){const k=d.k;if(!k)return;const row={time:Number(k.t)/1000,open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c),volume:Number(k.q),closed:!!k.x};state.lastKlineAt=Date.now();const i=state.klines.findIndex(x=>x.time===row.time);if(i>=0)state.klines[i]=row;else state.klines.push(row);state.klines=state.klines.slice(-500);renderChart();renderHeader()}
function onBookTicker(d){const bid=Number(d.b),ask=Number(d.a);if(bid&&ask){state.price=(bid+ask)/2;state.lastTickerAt=Date.now();setText("best-bid",fmt(bid));setText("best-ask",fmt(ask));setText("spread-value",`${((ask-bid)/state.price*10000).toFixed(2)} bp`);renderHeader()}}
async function loadHistory(){try{const rows=await json(`${CONFIG.rest}/klines?symbol=${CONFIG.symbol}&interval=1m&limit=500`);state.klines=rows.filter(x=>Number(x[6])<Date.now()).map(x=>({time:Number(x[0])/1000,open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[7]),closed:true}));state.prevClose=state.klines.at(-2)?.close||null;renderChart();log(`Loaded ${state.klines.length} closed Futures candles`,"good")}catch(e){state.errors++;log(`Kline history unavailable: ${e.message}`,"warn")}}
async function loadDerivatives(){try{const [oi,fi,premium,ratio]=await Promise.all([json(`${CONFIG.rest}/openInterest?symbol=${CONFIG.symbol}`),json(`${CONFIG.rest}/fundingRate?symbol=${CONFIG.symbol}&limit=1`),json(`${CONFIG.rest}/premiumIndex?symbol=${CONFIG.symbol}`),json(`https://fapi.binance.com/futures/data/globalLongShortAccountRatio?symbol=${CONFIG.symbol}&period=5m&limit=1`)]);state.oi=Number(oi.openInterest);state.funding=Number(fi?.[0]?.fundingRate??premium.lastFundingRate);state.mark=Number(premium.markPrice);state.index=Number(premium.indexPrice);state.ratios=ratio?.[0]||null;state.lastOiAt=state.lastFundingAt=state.lastRatioAt=Date.now();renderDerivatives();renderHeader();log("OI, funding and positioning feeds refreshed","good")}catch(e){state.errors++;log(`Derivative feed unavailable: ${e.message}`,"warn")}}
function setFeed(feed,status){const id=feed==="trades"?"tape-status":"book-status";setText(id,status);if(feed==="orderbook")setText("large-order-status",status)}
function bumpFeed(feed,message){state.errors++;setFeed(feed,"ERROR");log(message,"warn")}
function renderHeader(){setText("last-price",usd(state.price));const ch=state.prevClose&&state.price?((state.price-state.prevClose)/state.prevClose*100):null;setText("price-change",ch==null?"—":`${ch>=0?"+":""}${ch.toFixed(2)}%`);setClass("price-change",ch==null?"neutral":ch>=0?"up-text":"down-text");const b=[...state.buckets.values()].at(-1);const delta=b?b.buy-b.sell:null;setText("delta-value",delta==null?"—":usd(delta));setClass("delta-value",delta==null?"neutral":delta>=0?"up-text":"down-text");setText("delta-detail",b?`${b.count.toLocaleString()} executions · ${new Date(b.time).toISOString().slice(11,16)} UTC`:"No closed bucket yet");const m=bookMetrics();setText("book-imbalance",m.valid?`${m.imbalance>=0?"+":""}${m.imbalance.toFixed(1)}%`:"—");setClass("book-imbalance",m.imbalance>0?"up-text":m.imbalance<0?"down-text":"neutral");setText("book-detail",m.valid?`${m.bidShare.toFixed(1)}% bid / ${m.askShare.toFixed(1)}% ask`:"Order book syncing");setText("data-age",ago(Math.max(state.lastTradeAt,state.lastBookAt)));setText("data-age-detail",state.lastTradeAt?`Last trade ${ago(state.lastTradeAt)} ago`:"No tick received");const live=state.lastTradeAt>0&&state.book.valid;setText("market-state",live?(delta>0?"BUY PRESSURE":delta<0?"SELL PRESSURE":"BALANCED"):"WAITING");setClass("market-state",live?(delta>0?"up-text":delta<0?"down-text":"neutral"):"neutral");setText("market-state-detail",live?"Measurement only · no authorization":"Awaiting validated feeds");setText("sidebar-health",live?"LIVE / DEGRADED":"CONNECTING");setText("sidebar-health-detail",live?"Decision gate locked":"Connecting to Futures streams");setText("footer-event-age",ago(Math.max(state.lastTradeAt,state.lastBookAt)));setText("footer-status",live?"Validated Futures feeds active · execution disabled":"Initializing validated USD-M Futures feeds…");}
function bookMetrics(){const b=state.book;if(!b.valid)return{valid:false};const bids=[...b.bids.entries()].map(([p,q])=>({p:Number(p),q})).sort((a,c)=>c.p-a.p),asks=[...b.asks.entries()].map(([p,q])=>({p:Number(p),q})).sort((a,c)=>a.p-c.p);const mid=(bids[0]?.p+asks[0]?.p)/2||state.price,range=mid*.001;const bid10=bids.filter(x=>x.p>=mid-range).reduce((n,x)=>n+x.p*x.q,0),ask10=asks.filter(x=>x.p<=mid+range).reduce((n,x)=>n+x.p*x.q,0),total=bid10+ask10;return{valid:true,bids,asks,bid10,ask10,bidShare:total?bid10/total*100:50,askShare:total?ask10/total*100:50,imbalance:total?(bid10-ask10)/total*100:0,mid}}
function renderBook(){const m=bookMetrics();if(!m.valid){setText("book-age","Age —");return}const rows=[...m.asks.slice(0,CONFIG.bookLevels).reverse().map(x=>({...x,side:"ask"})),{p:m.mid,q:null,side:"mid"},...m.bids.slice(0,CONFIG.bookLevels).map(x=>({...x,side:"bid"}))];const max=Math.max(...rows.filter(x=>x.q).map(x=>x.q),1);$("orderbook").innerHTML=rows.map(x=>x.side==="mid"?`<div class="book-row" style="height:25px;border-top:1px solid #4b7088;border-bottom:1px solid #4b7088"><span></span><span class="price" style="color:var(--cyan);text-align:center;grid-column:1/-1">${fmt(x.p)}</span><span></span></div>`:`<div class="book-row ${x.side}"><span class="price">${fmt(x.p)}</span><span></span><span class="qty">${fmt(x.q,3)}</span><i class="depth-fill" style="width:${Math.min(100,x.q/max*100)}%"></i></div>`).join("");setText("bid-total",usd(m.bid10));setText("ask-total",usd(m.ask10));setText("book-sequence",`Sequence ${state.book.lastUpdateId||"—"}`);setText("book-age",`Age ${ago(state.lastBookAt)}`);renderLiquidity(m)}
function renderLiquidity(m=bookMetrics()){if(!m.valid)return;setText("liq-bid-notional",usd(m.bid10));setText("liq-ask-notional",usd(m.ask10));setText("liq-bid-share",`${m.bidShare.toFixed(1)}% of ±10bps displayed book`);setText("liq-ask-share",`${m.askShare.toFixed(1)}% of ±10bps displayed book`);const zones=estimatedZones();setText("liq-nearest",zones[0]?usd(zones[0].price):"—");$("liquidity-bars").innerHTML=zones.map(z=>`<div class="liq-zone"><span class="zone-price">${usd(z.price)}</span><span class="zone-bar" style="width:${Math.max(8,z.size/zones[0].size*100)}%"></span><span class="zone-size">${fmt(z.size,0)} BTC</span></div>`).join("");const large=[...m.asks.slice(0,20),...m.bids.slice(0,20)].filter(x=>x.p*x.q>250000).sort((a,b)=>b.p*b.q-a.p*b.q).slice(0,12);$("large-orders-table").innerHTML=large.length?large.map(x=>`<tr><td class="${x.p>m.mid?"sell-text":"buy-text"}">${x.p>m.mid?"ASK":"BID"}</td><td>${usd(x.p)}</td><td>${usd(x.p*x.q)}</td><td>${((x.p-m.mid)/m.mid*10000).toFixed(1)} bp</td><td>${ago(state.lastBookAt)}</td><td class="warning-text">UNCONFIRMED</td></tr>`).join(""): `<tr><td colspan="6" class="empty-state">No large validated resting orders in current range</td></tr>`}
function estimatedZones(){const p=state.mark||state.price||0,oi=state.oi||0;return[-.025,-.018,-.012,-.008,.008,.012,.018,.025].map((d,i)=>({price:p*(1+d),size:Math.max(25,oi*.00035*(1-Math.abs(d)*8)*(i%3===0?1.8:1))})).sort((a,b)=>Math.abs(a.price-p)-Math.abs(b.price-p)).slice(0,6)}
function renderTape(){const rows=state.trades.slice(0,CONFIG.maxTape);$("tape").innerHTML=rows.map(t=>`<div class="tape-row ${t.buy?"buy":"sell"}"><span>${new Date(t.ts).toISOString().slice(11,19)}</span><span>${fmt(t.price)}</span><span class="size">${usd(t.notional)}</span><span class="side">${t.buy?"BUY":"SELL"}</span></div>`).join("")||`<div class="empty-state">Waiting for Futures aggTrade</div>`}
function renderFlow(){const rows=[...state.buckets.values()].sort((a,b)=>a.time-b.time).slice(-12),max=Math.max(...rows.map(x=>Math.max(x.buy,x.sell)),1);$("footprint").innerHTML=rows.map(x=>{const d=x.buy-x.sell;return`<div class="flow-row"><span class="time">${new Date(x.time).toISOString().slice(11,16)}</span><span><i class="bar buy-bar" style="width:${Math.max(3,x.buy/max*100)}%"></i></span><span><i class="bar sell-bar" style="width:${Math.max(3,x.sell/max*100)}%"></i></span><span class="flow-num ${d>=0?"buy-text":"sell-text"}">${d>=0?"+":""}${usd(d)}</span></div>`}).join("")||`<div class="empty-state">Waiting for closed 1m buckets</div>`}
function renderChart(){if(!state.chart||!state.candleSeries)return;state.candleSeries.setData(state.klines.map(x=>({time:x.time,open:x.open,high:x.high,low:x.low,close:x.close})));state.volumeSeries?.setData(state.klines.map(x=>({time:x.time,value:x.volume,color:x.close>=x.open?"#4fe39b55":"#ff6f8555"})));setText("chart-last-update",`Last update ${ago(state.lastKlineAt)}`)}
function initChart(){if(!window.LightweightCharts)return;const el=$("price-chart");state.chart=LightweightCharts.createChart(el,{layout:{background:{color:"transparent"},textColor:"#7d98ad"},grid:{vertLines:{color:"#142a40"},horzLines:{color:"#142a40"}},rightPriceScale:{borderColor:"#1d3953"},timeScale:{borderColor:"#1d3953",timeVisible:true,secondsVisible:false},crosshair:{mode:1},width:el.clientWidth,height:405});state.candleSeries=state.chart.addCandlestickSeries({upColor:"#4fe39b",downColor:"#ff6f85",borderVisible:false,wickUpColor:"#4fe39b",wickDownColor:"#ff6f85"});state.volumeSeries=state.chart.addHistogramSeries({priceFormat:{type:"volume"},priceScaleId:"volume",scaleMargins:{top:.82,bottom:0},color:"#4c8"});new ResizeObserver(()=>state.chart?.applyOptions({width:el.clientWidth})).observe(el);renderChart()}
function renderDerivatives(){setText("oi-value",state.oi?fmt(state.oi,3):"—");setText("oi-age",state.lastOiAt?`Updated ${ago(state.lastOiAt)} ago`:"Unavailable");setText("funding-value",state.funding==null?"—":`${(state.funding*100).toFixed(4)}%`);setText("funding-state",state.funding==null?"Unavailable":state.funding>0?"Positive · long pays short":"Negative · short pays long");setText("mark-value",usd(state.mark));const r=state.ratios,long=Number(r?.longAccount)*100,short=Number(r?.shortAccount)*100;setText("positioning-value",Number.isFinite(long)?`${long.toFixed(1)}% LONG`:"—");setText("positioning-detail",Number.isFinite(long)?`Ratio ${Number(r.longShortRatio).toFixed(2)}`:"Public ratio unavailable");setText("long-ratio",Number.isFinite(long)?`Long ${long.toFixed(1)}%`:"Long —");setText("short-ratio",Number.isFinite(short)?`Short ${short.toFixed(1)}%`:"Short —");$("long-bar").style.width=`${Number.isFinite(long)?long:50}%`;$("short-bar").style.width=`${Number.isFinite(short)?short:50}%`;setText("ratio-status",r?"LIVE":"UNAVAILABLE");setText("basis-value",state.mark&&state.index?usd(state.mark-state.index):"—");setText("funding-regime",state.funding==null?"—":Math.abs(state.funding)>.0005?"EXTREME":"NORMAL")}
function feedRows(){const now=Date.now();return[{key:"Trades",label:"Futures aggTrade",status:state.lastTradeAt&&now-state.lastTradeAt<3000?"LIVE":"STALE",age:state.lastTradeAt?now-state.lastTradeAt:null,detail:"wss://fstream.binance.com"},{key:"Orderbook",label:"Local L2 order book",status:state.book.valid&&now-state.lastBookAt<1500?"LIVE":state.book.valid?"STALE":"INVALID",age:state.lastBookAt?now-state.lastBookAt:null,detail:`sequence ${state.book.lastUpdateId||"—"} · resync ${state.book.resyncs}`},{key:"Klines",label:"Closed Futures candles",status:state.lastKlineAt?"LIVE":"WAITING",age:state.lastKlineAt?now-state.lastKlineAt:null,detail:`${state.klines.length} rows · ${state.interval}`},{key:"Open Interest",label:"Open interest",status:state.oi!==null?"LIVE":"UNAVAILABLE",age:state.lastOiAt?now-state.lastOiAt:null,detail:"Binance Futures REST"},{key:"Funding",label:"Funding rate",status:state.funding!==null?"LIVE":"UNAVAILABLE",age:state.lastFundingAt?now-state.lastFundingAt:null,detail:"Binance Futures REST"},{key:"Liquidations",label:"Observed forceOrder",status:"UNAVAILABLE",age:null,detail:"No verified liquidation stream connected"},{key:"Macro / News",label:"Macro and news",status:"UNAVAILABLE",age:null,detail:"Not connected; never used for live decisions"}];}
function renderHealth(){const rows=feedRows(),critical=rows.slice(0,5),degraded=critical.some(x=>x.status!=="LIVE");setText("health-pill",degraded?"DEGRADED":"LIVE");setClass("health-pill",`pill ${degraded?"warning":""}`);$("health-grid").innerHTML=rows.map(x=>`<div class="health-card ${x.status==="LIVE"?"good":"warn"}"><div class="health-title"><h3>${x.label}</h3><span class="health-state ${x.status==="LIVE"?"good-text":"warning-text"}">${x.status}</span></div><div class="health-meta"><span>${esc(x.detail)}</span><span class="health-age">${x.age==null?"age —":`age ${(x.age/1000).toFixed(1)}s`}</span></div></div>`).join("");const live=!degraded;setClass("global-live-dot",`live-dot ${live?"":"warning"}`);setText("sidebar-health",live?"LIVE":"DEGRADED");setClass("sidebar-health-ring",`status-ring ${live?"":"warning"}`)}
function renderHealthLog(){$("health-log").innerHTML=state.events.map(x=>`<div class="log-line"><b>${x.time.toISOString().slice(11,19)} UTC</b><span class="${x.kind==="good"?"log-good":""}">${esc(x.message)}</span></div>`).join("")||`<div class="empty-state">No system events</div>`}
function renderDecision(){const m=bookMetrics(),b=[...state.buckets.values()].at(-1),checks=[{label:"Futures trade stream",ok:state.lastTradeAt&&Date.now()-state.lastTradeAt<3000,value:state.lastTradeAt?"LIVE":"WAITING"},{label:"L2 sequence validity",ok:m.valid,value:m.valid?"VALID":"INVALID"},{label:"Liquidation tape",ok:false,value:"UNAVAILABLE"},{label:"Historical calibration",ok:false,value:"UNAVAILABLE"},{label:"Execution authorization",ok:false,value:"LOCKED"}];$("decision-checks").innerHTML=checks.map(x=>`<div class="check-row"><span>${x.label}</span><b class="${x.ok?"ok":"bad"}">${x.value}</b></div>`).join("");setText("decision-reason",b?"Observed flow is displayed. Missing liquidation and calibration feeds keep execution locked.":"Waiting for complete, fresh and calibrated evidence.")}
function renderAll(){renderHeader();renderBook();renderTape();renderFlow();renderDerivatives();renderHealth();renderDecision()}
function setupNav(){document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view-panel").forEach(x=>x.classList.remove("active"));btn.classList.add("active");$("view-"+btn.dataset.view).classList.add("active");if(btn.dataset.view==="execution")setTimeout(()=>state.chart?.resize($("price-chart").clientWidth,405),50)}));document.querySelectorAll(".tf-btn").forEach(btn=>btn.addEventListener("click",async()=>{document.querySelectorAll(".tf-btn").forEach(x=>x.classList.remove("active"));btn.classList.add("active");state.interval=btn.dataset.interval;setText("chart-interval",state.interval);try{const rows=await json(`${CONFIG.rest}/klines?symbol=${CONFIG.symbol}&interval=${state.interval}&limit=500`);state.klines=rows.filter(x=>Number(x[6])<Date.now()).map(x=>({time:Number(x[0])/1000,open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[7]),closed:true}));state.candleSeries?.setData(state.klines.map(x=>({time:x.time,open:x.open,high:x.high,low:x.low,close:x.close})));state.volumeSeries?.setData(state.klines.map(x=>({time:x.time,value:x.volume,color:x.close>=x.open?"#4fe39b55":"#ff6f8555"})));log(`Switched to ${state.interval} closed Futures candles`,"good")}catch(e){log(`Interval load failed: ${e.message}`,"warn")}}));$("refresh-btn").addEventListener("click",()=>{state.book.valid=false;state.book.queue=[];syncBook();loadDerivatives();loadHistory()});$("clear-log").addEventListener("click",()=>{state.events=[];renderHealthLog()})}
async function boot(){setupNav();initChart();await Promise.all([loadHistory(),loadDerivatives()]);openStream();setInterval(loadDerivatives,30000);setInterval(renderHealth,1000);setInterval(renderHeader,1000);renderAll();log("Terminal booted in read-only research mode","good")}
boot();
